create or replace FUNCTION COUNT_TICKETS_FLIGHTS (IN_FL_NO VARCHAR2) RETURN NUMBER
IS
    V_COUNT_TICKET NUMBER;
BEGIN
        WITH pivot_tb1 AS (SELECT
            FLIGHT_NO,
            AIRCRAFT_CODE,
            BOOK_REF,    
            (COUNT(TICKET_NO)) AS TICKET_NO
        FROM FLIGHTS
        LEFT JOIN 
            (SELECT 
                TICKETS.BOOK_REF AS BOOK_REF,
                TICKET_FLIGHTS.FLIGHT_ID AS FLIGHT_ID,
                TICKET_FLIGHTS.TICKET_NO AS TICKET_NO
            FROM TICKETS 
            INNER JOIN TICKET_FLIGHTS 
                ON TICKETS.TICKET_NO = TICKET_FLIGHTS.TICKET_NO) PIV
        ON FLIGHTS.FLIGHT_ID = PIV.FLIGHT_ID
        GROUP BY FLIGHT_NO, AIRCRAFT_CODE, BOOK_REF)
        SELECT MAX(TICKET_NO)
             INTO V_COUNT_TICKET
             FROM pivot_tb1
             WHERE FLIGHT_NO = IN_FL_NO 
             GROUP BY FLIGHT_NO;
        RETURN V_COUNT_TICKET;
END;